"""Initial migration

Revision ID: eca31d367d6b
Revises: 
Create Date: 2026-01-18 18:49:59.713751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca31d367d6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_name', sa.String(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'reply_to')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'is_read')
    op.alter_column('reactions', 'emoji',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'])
    op.drop_index('ix_room_invites_id', table_name='room_invites')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'])
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rooms', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_rooms_name', table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index('ix_rooms_name', 'rooms', ['name'], unique=1)
    op.alter_column('rooms', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_room_invites_id', 'room_invites', ['id'], unique=False)
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reactions', 'emoji',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.BOOLEAN(), nullable=True))
    op.add_column('messages', sa.Column('reply_to', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'file_name')
    # ### end Alembic commands ###
